Feature/JJDZR11BB-12 - search by city
infoshareacademy/JJDZR11-BackendBoys pull request #6
Opened 2023-04-11 21:45 UTC by ThomasPlonski

- change name of package "browse" to "search" (+ refactor based on mvc model) and **add search by city method**,
- change cases in switches from int to static final,
- change "Menu" to abstract class "AppMenu".

2023-04-13 19:44 UTC, TomaszOdwald requested changes

2023-04-13 19:44 UTC, TomaszOdwald commented on src/main/java/org/example/abstractMenu/AppMenu.java
> +    protected abstract void printOptions();
Protected jest tutaj trochę na wyrost, bardziej pasuje tu public

2023-04-13 19:44 UTC, TomaszOdwald commented on src/main/java/org/example/request/RequestMenu.java
> +            System.out.println("Customer name: " + request.getRequester() + ", number: " + request.getContactNumber() + ".");
request.getContactNumber() sugeruje, że obiekt klasy Request ma jakiś swój numer kontaktowy, a jest to właściwość użytkownika i klasa User już ma taką metodę. W tym miejscu lepiej byłoby to zrobić przez request.getRequester().getContactNumber(), a metodę z klasy Request wyrzucić ;)

2023-04-13 19:44 UTC, TomaszOdwald commented on src/main/java/org/example/search/SearchMenu.java
> +    public void printOptions() {
Tu nie ma `@Override`, zapewne dlatego, że w AppMenu jest protected, a tu public ;)

2023-04-13 21:31 UTC, ThomasPlonski commented on src/main/java/org/example/request/RequestMenu.java
> +            System.out.println("Customer name: " + request.getRequester() + ", number: " + request.getContactNumber() + ".");
Zmieniłem dokładnie jak opisałeś :)

2023-04-13 21:32 UTC, ThomasPlonski commented on src/main/java/org/example/abstractMenu/AppMenu.java
> +    protected abstract void printOptions();
Ok, zmieniłem na public

2023-04-13 21:32 UTC, ThomasPlonski commented on src/main/java/org/example/search/SearchMenu.java
> +    public void printOptions() {
Zmieniłem na public i już jest Override :)

2023-04-14 14:00 UTC, TomaszOdwald approved these changes

2023-04-14 14:00 UTC, merged