Feature/JJDZR11BB-11 - information about already logged in user
infoshareacademy/JJDZR11-BackendBoys pull request #9
Opened 2023-04-12 22:37 UTC by ThomasPlonski

Added information about already logged in user -  Additional text in the top of the menu eg. "You are NOT logged in." or "You (Tomasz@wp.pl) are logged in".

Refers only to commit (17986e7 - Add information about already logged in user)

2023-04-13 20:11 UTC, TomaszOdwald commented
Na ten nawet nie patrzę, zanim nie zmergujesz poprzednich...

2023-04-15 09:06 UTC, ThomasPlonski commented
Konflikty rozwiązane, poproszę o approva :)

2023-04-15 09:16 UTC, TomaszOdwald requested changes

2023-04-15 09:16 UTC, TomaszOdwald commented on src/main/java/org/example/request/Request.java
> +    public String getContactNumber(User loggedUSer) {
Mówiłem, żeby tak nie robić. Skoro przekazujesz obiekt klasy User, tylko po to, żeby zwrócić jego numer, to jaki związek ma to z Requestem?

2023-04-15 09:16 UTC, TomaszOdwald commented on src/main/java/org/example/request/RequestMenu.java
> +    public static String getLoggedUser() {
Według mnie statyczna zmienna nie potrzebuje settera i gettera, skoro nie zawierają żadnej dodatkowej logiki, mogła zostać public.

2023-04-15 09:16 UTC, TomaszOdwald commented on src/main/java/org/example/request/RequestMenu.java
> +            System.out.println("Customer name: " + request.getRequester() + ", number: " + request.getContactNumber(userController.getUserByLogin(request.getRequester())) + ".");
j.w. - wystarczyłoby userController.getUserByLogin(request.getRequester()).getContactNumber() ;)

2023-04-16 08:14 UTC, ThomasPlonski commented on src/main/java/org/example/request/Request.java
> +    public String getContactNumber(User loggedUSer) {
Sorry, mój błąd przy rozwiązywaniu konfliktów. Już to zmieniałem w Pr (Feature/JJDZR11BB-12 - search by city #6), ale zastosowałem kod z PR o enumach, gdzie to nie było uwzględnione.

2023-04-16 08:14 UTC, ThomasPlonski commented on src/main/java/org/example/request/RequestMenu.java
> +    public static String getLoggedUser() {
Dzięki, zmieniłem to oraz zmieniłem też nazwę tej zmiennej z "loggedUser" na "loggedUserLogin", aby lepiej oddawała to co przechowuje - String z loginem a nie Usera.

2023-04-16 08:14 UTC, ThomasPlonski commented on src/main/java/org/example/request/RequestMenu.java
> +            System.out.println("Customer name: " + request.getRequester() + ", number: " + request.getContactNumber(userController.getUserByLogin(request.getRequester())) + ".");
zrobione

2023-04-16 09:09 UTC, merged